### ISSUE TITLE
Create token contract

### ISSUE THREAD

**Issue by spacecloudunit** [spacecloudunit/token#1]
- Limit to 150.000.000 units
- Decimals: 18
- Burnable
- Mintable
- Capped
- Pausable: Trigger allow transfer: yes/no

**Comment by kahmij** [comment]
Deploy the contract `Token(address sale_address)` where `sale_address` is the address from the crowdfund contract.

change the following variables:

```
    string public name = "BASIC ERC20 SALE";
    uint8 public decimals = 18;
    string public symbol = "BASIC";
    string public version = 'BASIC 0.1';
    address public mintableAdd
```

Source:
https://github.com/hunterlong/ethereum-ico-contract/blob/master/contracts/Token.sol

**Comment by kah-ja** [comment]
Deploy the contract `Token(address sale_address)` where `sale_address` is the address from the crowdfund contract.

change the following variables:

```
    string public name = "BASIC ERC20 SALE";
    uint8 public decimals = 18;
    string public symbol = "BASIC";
    string public version = 'BASIC 0.1';
    address public mintableAdd
```

source:
https://github.com/hunterlong/ethereum-ico-contract/blob/master/contracts/Token.sol

**Comment by kah-ja** [comment]
For burning tokens :
https://ethereum.stackexchange.com/questions/16188/best-way-to-burn-ethers-and-other-ethereum-tokens

**Comment by sprajcpf** [comment]
Trigger allow transfer: yes/no -> Pausable:
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/PausableToken.sol

**Comment by spacecloudunit** [comment]
contract SCU is Ownable, PausableToken, CappedToken, BurnableToken
