### ISSUE TITLE
Create crowdsale contract

### ISSUE THREAD

**Issue by spacecloudunit** [spacecloudunit/token#2]

**Comment by kah-ja** [comment]
`Sale(address _wallet)` where `address _wallet` held the ETH after the contibution.

change the following variables if needed:

```
        startBlock = block.number;
        maxMintable = 4000000000000000000000000; // 3 million max sellable (18 decimals)
        ETHWallet = _wallet;
        isFunding = true;
        creator = msg.sender;
        createHeldCoins();
        exchangeRate = 600;
```
source:
https://github.com/hunterlong/ethereum-ico-contract/blob/master/contracts/Sale.sol

**Comment by spacecloudunit** [comment]
Test sale contract developed, deployed on testnet and tested: https://ropsten.etherscan.io/address/0x2daE29E8887Dd1b69446EEEC64A873d976357b86

**Comment by spacecloudunit** [comment]
Done and working well in production
