### ISSUE TITLE
Deploy SCU Token contract on Ethereum foundation blockchain

### ISSUE THREAD

**Issue by spacecloudunit** [spacecloudunit/token#5]

**Comment by sprajcpf** [comment]
Deployed at 0xBD82A3C93B825c1F93202F9Dd0a120793E029BAD  
https://etherscan.io/address/0xbd82a3c93b825c1f93202f9dd0a120793e029bad
https://www.etherchain.org/account/bd82a3c93b825c1f93202f9dd0a120793e029bad
