### ISSUE TITLE
Create ERC20 token lock contract

### ISSUE THREAD

**Issue by spacecloudunit** [spacecloudunit/token#7]
Required functionality:
1. Initialize token lock contract with: payout address, start date, withdrawal percentage per month
2. Transfer tokens to token lock contract (ONCE). Block/Reject followup transfers
3. When start date is reached: Allow up to 1x"withdrawal percentage" to payout address
4. For each following month: withdrawal of 1x additional "withdrawal percentage" to payout address is possible

It should be possible to execute withdrawal multiple times. The maximum withdrawal amount cannot be exceeded

Example:
1. start payout date: 1.1.2019, withdrawal percentage per month: 4%
2. Send 100.000 Tokens to contract
3. When 1.1.2019 is reached up to 4.000 tokens can be withdrawal to payout address
4. When 1.2.2019 is reached up to 8.000 tokens can be withdrawal to payout address
....
27. When 1.2.2021 is reached withdrawal of 100.000 tokens to payout address is possible

**Comment by spacecloudunit** [comment]
https://github.com/radek1st/time-locked-wallets/blob/master/contracts/TimeLockedWallet.sol

**Comment by spacecloudunit** [comment]
- https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/TokenTimelock.sol
- https://github.com/radek1st/time-locked-wallets/blob/master/contracts/TimeLockedWallet.sol

**Comment by sprajcpf** [comment]
Solution: Use X-times the TokenTimeLock.sol by openzepplin

**Comment by spacecloudunit** [comment]
Next step: Deployment and test on test network

**Comment by spacecloudunit** [comment]
Test contracts deployed:
- https://ropsten.etherscan.io/address/0x7944331e7044311ce77d4e5b36e17dadf87db7f2
- https://ropsten.etherscan.io/address/0x3bcda4d6c836946688ffe6a382d0bc278342656d

**Comment by sprajcpf** [comment]
Unix times:
1. 01.02.2019 00:00 UTC: 1548979200
2. 01.03.2019 00:00 UTC: 1551398400
...<todo>...
25. 01.03.2021 00:00 UTC: : 1614556800

**Comment by sprajcpf** [comment]
Token lock contracts created and deployed: https://etherscan.io/find-similar-contracts?a=0x254ce6ef80e2cc27de450217d45ee6c824cc18c3
